# Generated by Django 5.0.3 on 2024-03-26 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_user_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Authorname', models.CharField(max_length=50)),
                ('Titlename', models.CharField(max_length=50)),
                ('Content', models.CharField(max_length=5000)),
                ('Published_date', models.DateField()),
                ('Published_time', models.TimeField()),
            ],
        ),
    ]
