# Generated by Django 5.0.3 on 2024-03-27 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_publisher'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisher',
            name='Blog_name',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='Published_time',
            field=models.CharField(max_length=50),
        ),
    ]
