# Generated by Django 5.0.3 on 2024-03-27 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_publisher_blog_name_alter_publisher_published_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisher',
            name='Blog_name',
            field=models.CharField(max_length=50),
        ),
    ]
