# Generated by Django 5.0.3 on 2024-04-05 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_publisher_blog_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisher',
            name='Published_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='Email',
            field=models.CharField(max_length=50),
        ),
    ]
