# Generated by Django 5.0.3 on 2024-04-05 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_publisher_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisher',
            name='Username',
            field=models.CharField(max_length=50),
        ),
    ]
