# Generated by Django 5.0.3 on 2024-04-05 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_publisher_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisher',
            name='Published_date',
            field=models.CharField(max_length=40),
        ),
    ]
