# Generated by Django 5.0.3 on 2024-04-05 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_publisher_published_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publisher',
            old_name='Username',
            new_name='User',
        ),
    ]
