# Generated by Django 5.0.3 on 2024-04-05 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_rename_username_publisher_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publisher',
            name='User',
        ),
    ]
