# Generated by Django 5.0.3 on 2024-04-05 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_remove_publisher_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisher',
            name='User',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
